docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build ./client -t "herrdermails/usi-elastic-rsi-client${tag}" .
    - docker push "$herrdermails/usi-elastic-rsi-client${tag}"
    - docker build ./server -t "$herrdermails/usi-elastic-rsi-server${tag}" .
    - docker push "$herrdermails/usi-elastic-rsi-server${tag}"
