version: "3.7"
services:
  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    restart: always
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - cluster.name=cluster_name
      - node.name=server_name
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - discovery.seed_hosts=["docker"] # hostname
      - discovery.type=single-node
      - xpack.security.enrollment.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD-SHELL", "curl -X GET -u elastic:${ELASTIC_PASSWORD} http://localhost:9200 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 120
  kibana:
    container_name: kibana
    depends_on:
      - es01
    image: docker.elastic.co/kibana/kibana:8.2.0
    restart: always
    volumes:
      - kibanadata:/usr/share/kibana/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - server.host=0.0.0.0
      - server.name=server_name
      - server.ssl.enabled=false
      - elasticsearch.hosts=["http://localhost:9200"]
      # fill those with random stuff (min 32 characters)
      - xpack.encryptedSavedObjects.encryptionKey=asasdasdaseoufghaskfihdsilhfsweiuo
      - xpack.security.encryptionKey=asasdasdaseoufghaskfihdsilhfsweiuo
      - xpack.reporting.encryptionKey=asasdasdaseoufghaskfihdsilhfsweiuo
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'"
        ]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  esdata01:
    driver: local
  kibanadata:
    driver: local
